### PR TITLE
Add max and min scores on pokerp end

### PR DESCRIPTION
**Pull request by lira92**
Add max and min scores on pokerp end

### CODE REVIEW

**Comment by lira92** [comment]
@jclg Can you accept this pull request?

**Comment by jclg** [comment]
@lira92 Thank you ;)

**Comment by lira92** [comment]
composer update isn't get my changes. Any idea?

**Comment by jclg** [comment]
Yeap, I forgot to update the projet on packagist. Can you try again please ?
Sorry for the slow response time. I am currently on vacation ;)

**Pull request merged**
